# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Hass FoundryVTT
version: "0.0.1"
slug: hass_foundryvtt
description: "Manage a FoundryVTT instance from Home Assistant"
url: "https://github.com/internetimagery/hass_foundryvtt"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
options:
  timed_url: ""
schema:
  timed_url: "str?"
startup: services
webui: "http://[HOST]:[PORT:30000]/"
ports:
  30000/tcp: 30000
